### ISSUE TITLE
Plotting functions for model fit

### ISSUE THREAD

**Issue by b-steve** [b-steve/acre#11]
Instead of having separate plotting functions, `show.Dsurf()`, `show.detfn()`, perhaps we should have a single plotting function where the user can select what type of plot using an argument, similar to the data plotting function. This way the user won't have to remember all of these different function names.

**Comment by JosephReps** [comment]
Looks like this has been implemented in `plot.acre_tmb,`. User can call plot like:

`plot.acre_tmb(x, type="survey")` or `plot.acre_tmb(x, type="detfn")`

for example.

Should be good to close this issue.
