### ISSUE TITLE
Replace existing bessel function with the in-built `besselI()` TMB function

### ISSUE THREAD

**Issue by b-steve** [b-steve/acre#14]
At the moment we use our own bessel function (top of `acreTMB.h`), which is used within the von-Mises PDF for observed bearings. My recollection is that models with observed bearings are surprisingly slow to fit, and I suspect the bessel function is the culprit.

TMB now has an in-built function `besselI()`. It would be worth redefining our von-Mises PDF to use this in-built function and compare model-fitting speed.

**Comment by b-steve** [comment]
Here's a TMB function for the von-Mises PDF, with output that matches `CircStats::dvm()`:

```
template<class Type>
Type dvm_stable(const Type &theta, const Type &mu, const Type &kappa, const int &give_log){
  Type out;
  out = kappa*(cos(theta - mu) - 1) - log(2*M_PI) - log(besselI(kappa, Type(0))/exp(kappa));
  if (give_log == 0){
    out = exp(out);
  }
  return out;
}
```

**Comment by JosephReps** [comment]
If I recall correctly, we compared these and it ended up being slower when using the TMB `besselI()`. 

Can run some tests again if needed, otherwise I think we can close this issue.
