### ISSUE TITLE
Allow `AIC()` to take multiple models as arguments

### ISSUE THREAD

**Issue by b-steve** [b-steve/acre#22]
When you use `AIC()` with `lm()`, you can include multiple models: `AIC(fit1, fit2, fit3)`.

In this package you can only apply `AIC()` to a single model at a time, but it would be nice if it could handle multiple.

**Comment by JosephReps** [comment]
New output from above:

```
> AIC.acre_tmb(dist_hn.fit, mul_ses.fit, workshop_fit)
 dist_hn.fit  mul_ses.fit workshop_fit 
   1289.1695     328.4918    -240.0933
```

Good to merge if you're happy <3

**Comment by b-steve** [comment]
Looks good! Small suggestion: how about we shoot for something similar to `lm()`, but with `npar` rather than `df`:

```r
> AIC(fit1, fit2, fit3)
     df      AIC
fit1  3 39.14748
fit2  4 40.80862
fit3  5 39.38762

```
