### ISSUE TITLE
Strange plotting errors

### ISSUE THREAD

**Issue by b-steve** [b-steve/acre#34]
When I ran my `acre` workshop, some users  (I think on Macs) got an error when they ran `plot(data, type = "capt")`. I can't replicate this error on Xubuntu. The error said something or other about a promise evaluation.

Others got an error when they ran this:
```
fit <- fit.acre(data, detfn = "hhn", model = list(D = ~ canopy.height))
plot(fit, type = "Dsurf")
```
I can replicate this error: 
```
Error in predict_D_for_plot(fit, session_select = ifelse(is.null(session),  : 
  object 'dist_mask' not found
```
But plotting does work fine when I include my own `new.data` argument.

**Comment by JosephReps** [comment]
Error was being caused by an oversight of my previous change to allow distance covariate plotting. When we don't provide new data, we just use the fit objects distance covariate, which is already contained within the location covariate df.

The following is the new output of the above code:

![image](https://github.com/user-attachments/assets/6b550df8-e343-49d4-be3e-6130b9662960)

Will do a bunch more testing to make sure everything is ok this time.

**Comment by JosephReps** [comment]
After playing around with the Dsurf plotting I have noticed, when I try to plot the Dsurf over a new mask, specified by xlim and ylim:

```
plot(fit, type="Dsurf", xlim=c(100,600), ylim=c(100,600), D.cov=list(
    "location" = data.frame(
    "x" = c(200, 300),
    "y" = c(300, 300),
    "canopy.height" = c(43, 21))
))
```

We get a warning:

```
Warning message:
In location_cov_to_mask(mask = list(list(x = c(100, 100, 100, 100,  :
  for 1'th element of 'loc.cov', the masks generated by the traps of 1'th session exceeds the area boundary provided too much, it is recommened to provide location related covariates with a larger range.
```
  
  I seems to me that this warning isn't appropriate here, as I'm providing the `D.cov` with my new covariate arguments.
  
  I may be incorrectly using this function, but if not perhaps a warning instead like:
  
```
 Warning:
  
 Location covariates contained within the fit object will be ignored as they lie too far from the generated mask. Additional location covariate data can be supplied with the "D.cov" argument
```

Or maybe not show a warning at all if we see there is some appropriate location covariate data supplied in `D.cov`

**Comment by b-steve** [comment]
Here's a new plotting issue using the current main branch. 

When I have multiple covariates, running `plot(data, type = "covariates", session = 1)` only shows a plot of one of them. I get asked `Hit <Return> to see next plot or <Esc> to cancel:`, but hitting `<Esc>` just exits the function instead of showing me the next covariate.
