### ISSUE TITLE
Covariate plots don't show negative values

### ISSUE THREAD

**Issue by b-steve** [b-steve/acre#4]
Calling `plot(data, type = "covariates")` shows white cells where covariate values are negative, but negative values are possible and should be displayed.

Here is an example:
```r
library(acre)
demo <- demo_fit("ihd", fit = FALSE)
demo$read_input$loc_cov$noise <- demo$read_input$loc_cov$noise - 10
data <- do.call("read.acre", demo$read_input)
plot(data, types = "covariates")
```

**Comment by 2345scy** [comment]
fixed in the commit 7842b52
