### ISSUE TITLE
Setting control components for `plot.acre_data()` returns an error

### ISSUE THREAD

**Issue by b-steve** [b-steve/acre#6]
Setting some of the `control` argument's components causes an error. For example, in the source code it looks like `arg_col` should be an allowable input but it causes an error:
```r 
demo <- demo_fit("ihd", fit = FALSE)
plot(demo$read_output, types = "covariates", session = 1,
     control = list(arg_col = list(n = 100, option = "D")))

Error in plot.acre_data(demo$read_output, types = "covariates", session = 1,  : 
  object '"covariates"' not found
```

I just had the same error when trying to use `control = list((plot_contours = FALSE)`, which I've fixed (see 05e3a24), and I think a similar fix needs to be applied elsewhere.

**Comment by 2345scy** [comment]
fixed in the commit 7842b52
